### ISSUE TITLE
Spacing title icon doesn't work

### ISSUE THREAD

**Issue by OxyFlax** [loregr/LGButton#13]
When I put a left icon (string:camera, font: io) and a title string, they are both at the opposite of the UIView. Icon is at the extreme left and text at the extreme right. Setting "Spacing title icon" doesn't allow me to bring them closer, only "Spacing leading" and "Spacing trailing" change something.

PS: My LGButton is in a stackview with trailing constraints.

<img width="279" alt="capture d ecran 2017-08-15 a 14 42 43" src="https://user-images.githubusercontent.com/14943003/29316393-26661210-81c8-11e7-81ec-22b34c6a1967.png">

**Comment by kwabford** [comment]
I believe I had the same problem. I fixed it by clearing (not setting to 0) all other spacing options and  setting "Spacing leading" to something high (i.e. 250). I was just stabbing in the dark but it got the results I wanted.

<img width="594" alt="screen shot 2017-08-18 at 2 59 26 pm" src="https://user-images.githubusercontent.com/385316/29478390-a0758b8e-843a-11e7-8dcb-51dbe964cfd9.png">

**Comment by OxyFlax** [comment]
Yeah I found that but this is not responsive. Change the device to iPhone 7+ or iPhone SE and you'll see the problem :(

**Comment by loregr** [comment]
The solution proposed by @kwabford is working and it is responsive, I've personally tested it. If it is still not working for you, please check some possible conflicting properties, or just share the properties of your button here so we can reproduce it locally.

**Comment by OxyFlax** [comment]
Ok that's true sorry, I put something high but not too much and it didn't fit with iPhone 7+ but now it's fine, thanks :)
