### ISSUE TITLE
Button appears grey by default and when the view is charging

### ISSUE THREAD

**Issue by OxyFlax** [loregr/LGButton#14]
The default background color should be clear but it's between dark grey and light grey for me.
Plus, when the view is charging at beginning we can see it grey instead of the chosen color (I'm using Storyboard).

**Comment by loregr** [comment]
I can't reproduce it, if you provide some context or share some code it would be helpful.

**Comment by OxyFlax** [comment]
<img width="660" alt="capture d ecran 2017-08-21 a 22 58 48" src="https://user-images.githubusercontent.com/14943003/29538055-588e5102-86c4-11e7-812f-fcc92f0dc9c6.png">
<img width="648" alt="capture d ecran 2017-08-21 a 22 59 01" src="https://user-images.githubusercontent.com/14943003/29538056-58a8f08e-86c4-11e7-89c3-8d00a8f0ee30.png">
I just put a UIView and change the Class to LGButton in IB and the view is grey instead of by default.

**Comment by OxyFlax** [comment]
This is because of line 54 from LGButton: 
`@IBInspectable public var bgColor: UIColor = UIColor.gray {` ;)

**Comment by OxyFlax** [comment]
Fixed in #15 and should be applied to master branch too

**Comment by loregr** [comment]
Aw right, I was working on an old local copy with the clear color, now I see. Btw that's the default style that I want it to have. Also by changing only the the bg color and keeping the title color to white, it won't be visible on the default white view controller background. Thanks anyway.

**Comment by OxyFlax** [comment]
Okay, but sometimes the background color set on the IB is not the one appearing when the view is charging. Hope it will help people figure out with this issue :)
