### ISSUE TITLE
Vertical alignment for image and title

### ISSUE THREAD

**Issue by toseefkhilji** [loregr/LGButton#2]
Nice UIControl !!

Just missing Vertical alignment for image and title. Like this.
![screen shot 2017-06-20 at 8 29 25 am](https://user-images.githubusercontent.com/2367614/27314628-b334d8b4-5592-11e7-85d5-5eb4b40dad7c.png)

I know It can be fix using `titleEdgeInsets` & `imageEdgeInsets`, but it would be great if control have this functionality too.

Thanks.

**Comment by loregr** [comment]
@toseefkhilji implemented in: https://github.com/loregr/LGButton/releases/tag/1.0.1
