### ISSUE TITLE
Transparent or non-opaque button backgrounds

### ISSUE THREAD

**Issue by annjawn** [loregr/LGButton#21]
Is there a way to make the button background transparent or non-opaque with alpha component less than 1? I pulled an IBOutlet into my VC as a `UIView` and attempted to set the `backgroundColor` to dark gray with alpha component 0.25 but that doesn't seem to work. Is it even possible?

Here's my code

```
@IBOutlet weak var cameraButton: UIView!
cameraButton.isOpaque = false
cameraButton.backgroundColor = UIColor.darkGray.withAlphaComponent(0.25)
```

**Comment by softmarshmallow** [comment]
With what solution this thread is closed??
