### ISSUE TITLE
Left Align Content

### ISSUE THREAD

**Issue by kevinmann** [loregr/LGButton#22]
I was just wondering how to left align the content of the button, I can not get it working. This is the code I am using, with auto layout constaints to fill the button to a set width. 

```
    let test: LGButton = {
        let lg = LGButton()
        lg.leftIconFontName = "io"
        lg.leftIconColor = UIColor.brandWhite
        lg.leftIconString = "social-youtube"
        lg.titleFontName = "AvenirNext-Bold"
        lg.leftIconFontSize = 18
        lg.titleFontSize = 18
        lg.cornerRadius = 16
        lg.titleString = "Show video"
        return lg
    }()
```

As you can see in the image below, the title is right aligning and if I set the `spacingLeading` or the `spacingTrailing` the all the content just centres when I would like it to be left aligned.

![Imgur](https://i.imgur.com/K6flQPi.png)
I am aiming for it to look like this (Have not set the right font sizes or colours yet):
![Imgur](https://i.imgur.com/RtobZFN.png)

**Comment by loregr** [comment]
@kevinmann this is not something achievable with the current implementation, I'll definitely take it in mind for future releases.

**Comment by kevinmann** [comment]
Ok thank you, I will try to see if I can add the functionality and create a pull request if that is useful.

**Comment by ZacharyKhan** [comment]
+1 on this, I think it's very important to have this feature. Without it, I cannot use the library as the button text is not centered.

**Comment by loregr** [comment]
Feature added in [v1.1](https://github.com/loregr/LGButton/releases/tag/1.1)
