### ISSUE TITLE
Preview dissapears from Storyboard

### ISSUE THREAD

**Issue by abrahamramirez** [loregr/LGButton#23]
Hi, i was designing a view in the story board when I opened again XCode all the Buttons, are not visible. They are still there, but I can´t view then in the Storyboard.

**Comment by supermnemonic** [comment]
try open storyboard. go to Editor -> Refresh All Views. It fixed for me.

**Comment by loregr** [comment]
Fixed in [v1.1](https://github.com/loregr/LGButton/releases/tag/1.1). If the error still occurs, please try @supermnemonic suggestion.
