### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aiswaryamanal** [loregr/LGButton#25]
A lot of errors in pod files. SwiftIconFont.Swift and Fontloader.swift have some error

**Comment by aiswaryamanal** [comment]
While type-checking 'icon' at /Projects/Glomium/Pods/LGButton/LGButton/Classes/SwiftIconFont/SwiftIconFont.swift:60:12

**Comment by aiswaryamanal** [comment]
While type-checking expression at [/Projects/Glomium/Pods/LGButton/LGButton/Classes/SwiftIconFont/SwiftIconFont.swift:68:3 - line:68:267] RangeText="drawText!.draw(in: CGRect(x:0, y:0, width:imageSize.width, height:imageSize.height), withAttributes: [NSAttributedString.font : UIFont.icon(from: font, ofSize: size), NSAttributedString.paragraphStyle: paragraphStyle, NSAttributedString.foregroundColor: iconColor])"

**Comment by thatmarcel** [comment]
You can just replace NSAttributedString.font with NSFontAttributeName and everything should work with Swift 3.
