### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by manucheri** [loregr/LGButton#26]
In addition to CocoaPods I think Carthage support would be nice to have.

I might have time to help implement this in the future, but submitting an issue now in case someone feels up to the task.

Carthage info: https://github.com/Carthage/Carthage

I think the only thing that needs to be changed is making the schemes for building the framework 'shared'.

Releases are already tagged according to SemVer, which Carthage will respect automatically, so that is already done.

**Comment by aanuza** [comment]
using https://github.com/aanuza/LGButton/tree/carthage_support

**Comment by LinusU** [comment]
@loregr would you accept a PR for this?

**Comment by loregr** [comment]
@LinusU sure, PRs are more than welcome :)
