### ISSUE TITLE
Add IBAction for Button

### ISSUE THREAD

**Issue by AbhishekJ17** [loregr/LGButton#28]
I create LGButton IBAction method, But not performing any action which, if your hold that button form a minute then it perform IBAction function.
It happen in one touch like normal button

**Comment by dafurman** [comment]
I've noticed this issue too. A workaround is to add a UITapGestureRecognizer to the button and to use that for functionality.

**Comment by rydamckinney** [comment]
When you create the IBAction, selected the sender as LGButton and select the event as "Touched Up Inside". That should create the proper trigger for you.

**Comment by loregr** [comment]
Please check @rydamckinney suggestion if you have this type of issue
