### ISSUE TITLE
pod install not working

### ISSUE THREAD

**Issue by annjawn** [loregr/LGButton#3]
Added to pod as

`pod 'LGButton'`

But keep getting this error upon `pod install`

`[!] Unable to find a specification for 'LGButton'`

Swift 3, Xcode 8

**Comment by basvankuijck** [comment]
Have you tried `pod install --repo-update` ?

**Comment by loregr** [comment]
@annjawn were you able to make it work? If yes please close this issue, otherwise please provide more info so the community can help you.

**Comment by annjawn** [comment]
@loregr sorry for the late response, unfortunately I moved on with using a different solution since I wasn't able to install the LGButton pod at all. 🙁

**Comment by emarthinsen** [comment]
FWIW, I had the same problem and it was because I didn't run `pod install --repo-update`.
