### ISSUE TITLE
Modify disabled colour

### ISSUE THREAD

**Issue by Johnne25** [loregr/LGButton#30]
Can you make it so that we can define what the button will look like when its disabled?
Right now the enabled and disabled button look extremely simular.

**Comment by loregr** [comment]
You can subclass `LGButton` and create your own disabled state by checking `isEnable` property, it's not that hard with all the `LGButton` features. Adding all the properties for another state will make the list of editable properties too long and almost unreadable. I prefer to keep this library the leanest that I can.
