### ISSUE TITLE
border looks not good!

### ISSUE THREAD

**Issue by danhhgl** [loregr/LGButton#33]
I want the border color is white, and the superview background is white too. It looks not good! How to solve this issue?
<img width="221" alt="screen shot 2018-06-14 at 6 37 08 pm" src="https://user-images.githubusercontent.com/19302957/41409910-09a1493c-7002-11e8-9f2b-e4cbc674d902.png">

**Comment by sharonjl** [comment]
Try setting border width to 0, that should remove the artifact.

**Comment by stockgainsmobile** [comment]
Have the same issue when button is rounded and border with > 0

**Comment by loregr** [comment]
Will check this out, thanks for reporting.

**Comment by stockgainsmobile** [comment]
Can I help do something? If i figure it out on my end ill send back a PR but if you have any ideas what can be causing it let me know.

**Comment by loregr** [comment]
@stockgainsmobile this should be fixed in [v1.1.6](https://github.com/loregr/LGButton/releases/tag/1.1.6). Please check it out and let me know if that's not the case. Thanks

**Comment by stockgainsmobile** [comment]
Hey brother it works like a charm! Thank you! Feel free to close

**Comment by loregr** [comment]
I'm glad to hear that :). Thanks @stockgainsmobile
