### ISSUE TITLE
Tap gesture conflict

### ISSUE THREAD

**Issue by combef-luna** [loregr/LGButton#37]
I use an IBAction with event "Touched up inside" and my view controller has also a UITapGestureRecognizer. When I touch my button the IBAction is not called because the tap gesture prevail. That is not the case with a UIButton.
I found that some UIControl functions setting the Hilighted property are override in the LGButton class and that is not the case in UIButton class.

The solution I used is to use my view controller as a delegate of my gesture recognizer and to check if the location of the tap is inside my button bounds.

**Comment by loregr** [comment]
Fixed in [v1.1](https://github.com/loregr/LGButton/releases/tag/1.1).
