### ISSUE TITLE
Update for Swift 4.2 in pod

### ISSUE THREAD

**Issue by Innomalist** [loregr/LGButton#45]
Hello,
I was just going to send a pull request for updating to swift 4.2 but i noticed the source code is on swift 4.2 only the update hasn't been delivered to cocoapods. So if you could, please bump your version with new changes you have already made.

Thanks in advance

**Comment by loregr** [comment]
Fixed in [v1.1](https://github.com/loregr/LGButton/releases/tag/1.1).
