### ISSUE TITLE
Make LGButton open, so subclassable ? 

### ISSUE THREAD

**Issue by 10000TB** [loregr/LGButton#54]
For example, we need to patch some handy instance functions for the button, I would naturally think we can subclass it, then we can use the shared handy function everywhere, and make UI configs consistent

sth like: 
```
clsss CustomButton: LGButton {
     init(withButtonTitle){
         super.init()
          // custom config
          // ....
     }
    
      func enableButton() {
          self.isEabled = true
          // other custom UI change to enabled button
          // ...
       }
       func disableButton() {
          // counterpart to enableButton.
        }
        
         //.. other functions needed per custom requirements
}
```

**Comment by 10000TB** [comment]
I integrated LGButton as pod module, notice that in swift 4.2 LGButton is public but not open, so xcode throws following error when I tried to subclass it.

`Cannot inherit from non-open class 'LGButton' outside of its defining module`

Any suggestion ?

**Comment by loregr** [comment]
@10000TB Thanks for your report. The fix is now available in [v1.1.3](https://github.com/loregr/LGButton/releases/tag/1.1.3).

**Comment by 10000TB** [comment]
@loregr  seems like with the new change, it is still not subclassable, there is not a good designated method could be called from super

```
Must call a designated initializer of the superclass 'LGButton'
```

**Comment by 10000TB** [comment]
sth like `super.init(nibName: nil, bundle: nil)`
