### ISSUE TITLE
Updated google plus icon

### ISSUE THREAD

**Issue by n1schal** [loregr/LGButton#55]
How do I get the updated google plus icon from font awesome? When I set the corresponding values to fa and google-plus-g, I don't see the updated Google Plus. 

Any help would be much appreciated! Thanks!

**Comment by loregr** [comment]
Hi @n1schal , I've just released [v1.1.4](https://github.com/loregr/LGButton/releases/tag/1.1.4) which includes an update to FontAwesome. You can find the cheatsheet [here](https://fontawesome.com/v4.7.0/icons/). So in your case you should set `fa` and `google-plus`. I'm going to close the issue, but feel free to reopen or  comment if you have further questions. Thanks.
