### ISSUE TITLE
FontAwesome.ttf file not found, crashes app

### ISSUE THREAD

**Issue by l3bel** [loregr/LGButton#56]
fontURL is nil (FontAwesome.ttf file no longer found in the resources folder) causing FontLoader.swift  to crash at line 26: let data = try Data(contentsOf: fontURL!)

**Comment by l3bel** [comment]
@loregr I just saw the FontAwesome.ttf file now resides at the root path of the repository?!

**Comment by loregr** [comment]
@l3bel thank for reporting it. It is now fixed in [v1.1.5](https://github.com/loregr/LGButton/releases/tag/1.1.5).
