### ISSUE TITLE
Can you have a statically sized button and center the icon and title?

### ISSUE THREAD

**Issue by c0state** [loregr/LGButton#57]
Is it possible to have a statically defined width (or one constrained by autolayout) and have the title and icon/image centered in the middle of the button? Right now, it looks like if I use autolayout or statically define a button size, that the title and icon will be aligned to the button edges.

**Comment by l3bel** [comment]
@c0state I believe this can be achieved by tweaking the "Spacing ..." properties - and it's a good idea anyway to reset these to 0, their default values may not always suit your needs. @loregr ?

**Comment by loregr** [comment]
Exactly. As @l3bel said, once you've fixed the width of the button you need to play with spacing properties to center the content. In particular with `spacingLeading`, `spacingTrailing` and `spacingTitleIcon` properties.
