### ISSUE TITLE
Still get black border arounded rounded image

### ISSUE THREAD

**Issue by stockgainsmobile** [loregr/LGButton#60]
**Describe the bug**
https://github.com/loregr/LGButton/issues/33

**To Reproduce**
Round a button fully
add a white border
voila
the circle has a black very thin border

This is the same issue reported in issue 33, was this resolved?

**Comment by loregr** [comment]
@stockgainsmobile  If a bug already exists and you've already commented on it, there's no need to spam by creating again another issue and link the previous one in less then a day. Just wait and give people the time to check your report. I'm closing this issue and reopen #33 so we can track the history of the problem there. Thanks.

**Comment by stockgainsmobile** [comment]
@loregr my bad I saw that the other ticket was closed so I was thinking we could use another ticket to track it. Anyways thanks for responding on this promptly. Cheers
