### ISSUE TITLE
WOFF2 support

### ISSUE THREAD

**Issue by bre7** [loregr/LGButton#8]
Have you tried using WOFF2 assets instead of TTF/OTF ? File-size is reduced greatly (asset folder goes from 897KB to 282KB)

There's no real info about official support other than the announcement in Safari's patch notes (WOFF2 works in iOS >= 10). Adding support for WOFF2 (with WOFF fallback for earlier iOS versions) is quite simple since it only required modifying a single line of code

Maybe push it as a new sub-spec ?

**Comment by loregr** [comment]
Thanks for the suggestion, but I prefer to keep using the most common TTF/OTF format.
